#!/bin/sh

echo "executing pre-commit hooks checks with args [$@]"

#######################
# Linter & Formatting #
#######################
echo "executing formatter & linter..."

check=true
# staged files (not deleted ones)
staged_files=$(git diff --diff-filter=d --name-only --staged | grep .js)

no_staged_files=$(echo $staged_files | sed 's/ /\n/g' | wc -l)

if [[ $no_staged_files -ne 0 ]];
then
      echo "files that are staged (excluding deleted ones): "
      echo "$staged_files"

      for FILE in $staged_files
            do
                  prettier --write "${FILE}"
                  # stage that file again (just in case it's prettified)
                  git add $FILE
            done
fi

if [ "$check" = true ]; 
then
      echo 'lint check passed'
else 
      echo "lint check failed"
      exit 1
fi
